---
# tasks file for gitlab
- name: apt update and install package
  apt:
    name:
      - ca-certificates
      - curl
      - openssh-server
      - postfix
      - tzdata
      - perl
    state: present
    update_cache: yes

- name: push gitlab-ce to host
  ansible.posix.synchronize:
    src: "{{ gitlab_package_deb }}"
    dest: "{{ gitlab_package_deb }}"
  delegate_to: gitlab

- name: install gitlab-ce
  apt:
    deb: "{{ gitlab_package_deb }}"/gitlab-ce_17.8.0-ce.0_amd64.deb
  delegate_to: gitlab
  become: true

- name: include gitlab config
  include_tasks:
    name: gitlab_config.yml
