apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-website
  namespace: dev-ns
  labels:
    name: devops-website
    instance: devops-website
data:
  API_URL: http://api.devops.com
  APP_URL: http://app.devops.com
  DB_URL: http://db.devops.com
  DB_USER: devops
  DB_PASSWORD: devops
---
apiVersion: v1
kind: Service
metadata:
  name: devops-website
  namespace: dev-ns
  labels:
    name: devops-website
    instance: devops-website
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: devops-website
    instance: devops-website
---
