---
- name: config postgresql
  lineinfile:
    path: "{{ postgresql_path }}"
    regexp: '^#listen_addresses = 'localhost''
    line: 'listen_addresses = {{item}}'
    owner: root
    group: root
    mode: 0644
  with_items: "{{ groups.postgres }}"

- name: config pg_hba
  lineinfile:
    path: "{{ pg_hba_path }}"
    line: 'host    all          gitlab         {{ ansible_ssh_host }}/{{ prefix }}                md5'
    owner: root
    group: root
    mode: 0644

- name: Config_postgres_db
  postgresql_db:
    db: gitlabhq_production
    login_user: postgres
    login_host: "{{ ansible_ssh_host }}"

- name: Config postgres user
  postgresql_user:
    db: gitlabhq_production 
    user: gitlab
    password: "{{ vault }}"
    login_user: postgres
    login_host: "{{ ansible_ssh_host }}"

- name: Config postgres privs
  postgresql_privs:
    db: gitlabhq_production
    state: present
    roles: gitlab
    privs: ALL
    objs: public
    type: schema
    login_user: postgres
    login_host: "{{ ansible_ssh_host }}"
