---
- name: change external_url
  lineinfile:
    path: "{{ gitlab_rb }}"
    regexp: '^external_url 'http://gitlab.example.com''
    line: 'external_url 'http://{{item}}''
    owner: root
    group: root
    mode: 0644
  with_items: "{{ groups.gitlab }}"

- name: change gitlab config 1
  lineinfile:
    path: "{{ gitlab_rb }}"
    regexp: '^# postgresql['enable'] = true'
    line: 'postgresql['enable'] = false'
    owner: root
    group: root
    mode: 0644

- name: change gitlab config 2
  lineinfile:
    path: "{{ gitlab_rb }}"
    regexp: '^# gitlab_rails['db_adapter'] = "postgresql"'
    line: 'gitlab_rails['db_adapter'] = "postgresql"'
    owner: root
    group: root
    mode: 0644

- name: change gitlab config 3
  lineinfile:
    path: "{{ gitlab_rb }}"
    regexp: '^# gitlab_rails['db_encoding'] = "unicode"'
    line: 'gitlab_rails['db_encoding'] = "unicode"'
    owner: root
    group: root
    mode: 0644

- name: change gitlab config 4
  lineinfile:
    path: "{{ gitlab_rb }}"
    regexp: '^# gitlab_rails['db_host'] = nil'
    line: 'gitlab_rails['db_host'] = '{{item}}''
    owner: root
    group: root
    mode: 0644
  with_items: "{{ groups.postgres }}"

- name: change gitlab config 5
  lineinfile:
    path: "{{ gitlab_rb }}"
    regexp: '^# gitlab_rails['db_password'] = nil'
    line: '# gitlab_rails['db_password'] = {{ vault }}'
    owner: root
    group: root
    mode: 0644


- name: change gitlab config 6
  lineinfile:
    path: "{{ gitlab_rb }}"
    regexp: '^# gitlab_rails['db_username'] = "gitlab"'
    line: 'gitlab_rails['db_username'] = "gitlab"'
    owner: root
    group: root
    mode: 0644
    