- name: print msg
  debug:
    msg: directory is test

- name: Create directory
  ansible.builtin.file:
    path: /opt/prod
    state: directory

- name: Sync repository to remote server
  ansible.posix.synchronize:
    src: /builds/milad/project1
    dest: /opt/prod

- name: Run main script on server
  shell:
    cmd: cd "/opt/prod/project1" && bash main.sh
