variables:
  IMAGE_NAME: project2

stages:
  - Build
  - Deploy

build:
  stage: Build
  image: docker
  script:
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD" # https://reg.sudoix.local/
    - docker build -t 9350733512/$IMAGE_NAME:$CI_PIPELINE_ID .
    - docker push 9350733512/$IMAGE_NAME:$CI_PIPELINE_ID

deploy:
   stage: Deploy
   before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOYER_PRIVATE_KEY" >> ~/.ssh/id_ed25519
    - cat ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

   script:
    - unset DOCKER_HOST
    - docker context create my-swarm --docker "host=ssh://milad@192.168.178.10"
    - docker context use my-swarm
    - docker node ls
    - docker stack rm $IMAGE_NAME
    - sed -i "s/latest/$CI_PIPELINE_ID/g" docker-compose.yml
    - cat docker-compose.yml
    - docker stack deploy -c docker-compose.yml $IMAGE_NAME
   needs:
    - build
   retry: 2