---
# tasks file for basic

- name: Install Azabbix and Requirment
  apt:
    name:
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php8.3-pgsql
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent
      - postgresql
      - postgresql-contrib
    state: present
  when: ansible_facts['os_family'] == "Debian"

    #- name: Create the users
    #  community.postgresql.postgresql_user:
    #    name: zabbix
    #    password: 123456
    #    login_user: postgres

- name: Change pq_hba.conf to md5
  lineinfile:
    path: /etc/postgresql/16/main/pg_hba.conf
    regexp: '^local   all             postgres                                peer'
    line: 'local   all             postgres                                md5'
    owner: root
    group: root
    mode: 0644

- name: Restart postgres services
  service:
    name: postgresql
    state: restarted

- name: Create User
  community.postgresql.postgresql_user:
    name: zabbix
    password: 123456
    login_user: postgres
    login_password: 123456

- name: Create DB
  community.postgresql.postgresql_db:
    name: zabbix
    login_user: postgres
    login_password: 123456

- name: Add Password in Database Config File
  lineinfile:
    path: "{{ db }}"
    regexp: '^# DBPassword='
    line: 'DBPassword=123456'
    owner: root
    group: root
    mode: 0644

- name: Restart zabbix services
  service:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: Restart zabbix services
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: Restart zabbix services
  service:
    name: apache2
    state: restarted
    enabled: yes
